/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GQmc2HJkX6D
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:
 * 
import { Chivo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export default function Dashboard() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <section className="py-12 md:py-20">
        <div className="container mx-auto px-4 md:px-6">
          <div className="mb-8 md:mb-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-2">Active Programming Lobbies</h2>
            <p className="text-gray-500">Join a lobby and compete against other programmers.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardTitle>Algorithms Challenge</CardTitle>
                <CardDescription>Solve complex algorithmic problems and climb the leaderboard.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-gray-500">Participants: 24</span>
                  <span className="text-gray-500">Ends in: 2h 15m</span>
                </div>
                <div className="flex justify-end">
                  <a
                    className="inline-flex items-center justify-center px-4 py-2 bg-[#0077b6] text-white font-medium rounded-md hover:bg-[#00a8e8] transition-colors"
                    href="#"
                  >
                    Join
                  </a>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Data Structures Challenge</CardTitle>
                <CardDescription>Implement and optimize data structures to solve complex problems.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-gray-500">Participants: 18</span>
                  <span className="text-gray-500">Ends in: 1h 45m</span>
                </div>
                <div className="flex justify-end">
                  <a
                    className="inline-flex items-center justify-center px-4 py-2 bg-[#0077b6] text-white font-medium rounded-md hover:bg-[#00a8e8] transition-colors"
                    href="#"
                  >
                    Join
                  </a>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Dynamic Programming Challenge</CardTitle>
                <CardDescription>Solve complex problems using dynamic programming techniques.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-gray-500">Participants: 32</span>
                  <span className="text-gray-500">Ends in: 3h 00m</span>
                </div>
                <div className="flex justify-end">
                  <a
                    className="inline-flex items-center justify-center px-4 py-2 bg-[#0077b6] text-white font-medium rounded-md hover:bg-[#00a8e8] transition-colors"
                    href="#"
                  >
                    Join
                  </a>
                </div>
              </CardContent>
            </Card>
          </div>
          <div className="mt-8 md:mt-12 flex justify-center">
            <a
              className="inline-flex items-center justify-center px-6 py-3 bg-[#0077b6] text-white font-medium rounded-md hover:bg-[#00a8e8] transition-colors"
              href="#"
            >
              Create a New Lobby
            </a>
          </div>
        </div>
      </section>
      <section className="bg-gray-100 dark:bg-gray-800 py-12 md:py-20">
        <div className="container mx-auto px-4 md:px-6">
          <div className="mb-8 md:mb-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-2">Platform Updates and News</h2>
            <p className="text-gray-500">Stay up-to-date with the latest changes and announcements.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardTitle>New Leaderboard Feature</CardTitle>
                <CardDescription>
                  We've added a new leaderboard feature to track your progress and compare your skills with other users.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex justify-end">
                  <a
                    className="inline-flex items-center justify-center px-4 py-2 bg-[#0077b6] text-white font-medium rounded-md hover:bg-[#00a8e8] transition-colors"
                    href="#"
                  >
                    Read More
                  </a>
                </div>
              </CardContent>
            </Card>     
            <Card>
              <CardHeader>
                <CardTitle>Improved Lobby Filtering</CardTitle>
                <CardDescription>
                  We've updated the lobby filtering system to make it easier to find the right challenge for your skill
                  level.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex justify-end">
                  <a
                    className="inline-flex items-center justify-center px-4 py-2 bg-[#0077b6] text-white font-medium rounded-md hover:bg-[#00a8e8] transition-colors"
                    href="#"
                  >
                    Read More
                  </a>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>New Problem Sets Released</CardTitle>
                <CardDescription>
                  We've added a new set of challenging problems for you to solve and improve your balls.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex justify-end">
                  <a
                    className="inline-flex items-center justify-center px-4 py-2 bg-[#0077b6] text-white font-medium rounded-md hover:bg-[#00a8e8] transition-colors"
                    href="#"
                  >
                    Read More
                  </a>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}
